### ISSUE TITLE
新手小白cry for help

### ISSUE THREAD

**Issue by tiloulou177** [todd5167/flink-spark-submiter#8]
todd5167，hello：
    请教一下，flink-submiter项目和flink-java项目相互独立的是么？那flink-submiter项目还需打包么，直接在idea运行主类LauncherMain会找不到jar包，jar包所在机器和flink安装的机器和kafka集群（参数--bootstrapServers）都不一样，那buildJobParamsInfo()方法里面的参数runJarPath，flinkConfDir应该如何配置呢？还有我只需要flink-yarn-submiter的话，那examples和common目录是不是不需要了呢？

**Comment by tiloulou177** [comment]
如果把flink-yarn-submiter放到我的flink-java项目里面，那打jar时主类指定为?flink-yarn-submiter的主类是LaucherMain而不是KafkaReader对吧？

**Comment by tiloulou177** [comment]
如想在本地测试的话，在本地windows安装好flink和hadoop，可以运行么，是在idea终端运行本地jar包还是直接运行LaucherMain的main函数呢？

**Comment by tiloulou177** [comment]
hi:
我现在的配置runJarPath和hadoop,flink都在同一台机器上A，--bootstrapServer配置的是kafka的3台机器B,C,D，也就是我打包到A上之后，在A上运行java -cp xxx.jar mainClass会在JobGraphBuildUtil的75行createJobGraph()的时候报错，能请教一下如何解决么？

**Comment by todd5167** [comment]
@tiloulou177     window系统没办法直接提交到Yarn集群

**Comment by todd5167** [comment]
@tiloulou177  createJobGraph()的时候报错，得具体看看错误日志。

**Comment by tiloulou177** [comment]
> @tiloulou177 window系统没办法直接提交到Yarn集群

**Comment by tiloulou177** [comment]
>  window系统没办法直接提交到Yarn集群

windows安装hadoop和flink之后也不行么？

**Comment by tiloulou177** [comment]
>createJobGraph()的时候报错，得具体看看错误日志。
运行jar包报错信息如下：
--------------------------------------------------------------------------------------------------------------------------------
......
INFO [main] - Loading configuration property: jobmanager.execution.failover-strategy, region
 INFO [main] - Loading configuration property: rest.bind-port, 50100-50200
 INFO [main] - Loading configuration property: io.tmp.dirs, /tmp
 INFO [main] - Loading configuration property: historyserver.web.address, dataMiddle-93
 INFO [main] - Loading configuration property: historyserver.archive.fs.dir, hdfs://master/flink/ha/completed-jobs/
 INFO [main] - Loading configuration property: resourcemanager.taskmanager-timeout, 900000
Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: The program caused an error:

Classpath: [file:/opt/runJar/flink-job-submit-test0105.jar]

**System.out: (none)

System.err: (none)
        at org.apache.flink.client.program.PackagedProgramUtils.generateException(PackagedProgramUtils.java:245)
        at org.apache.flink.client.program.PackagedProgramUtils.getPipelineFromProgram(PackagedProgramUtils.java:164)
        at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:77)
        at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:109)
        at com.yss.datamiddle.flinkYarnSubmiter.utils.JobGraphBuildUtil.buildJobGraph(JobGraphBuildUtil.java:75)**
        at com.yss.datamiddle.flinkYarnSubmiter.executor.YarnJobClusterExecutor.submit(YarnJobClusterExecutor.java:73)
        at com.yss.datamiddle.flinkYarnSubmiter.launcher.LauncherMain.submitFlinkJob(LauncherMain.java:55)
        at com.yss.datamiddle.flinkYarnSubmiter.launcher.LauncherMain.main(LauncherMain.java:188)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:288)
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:198)
        at org.apache.flink.client.program.PackagedProgramUtils.getPipelineFromProgram(PackagedProgramUtils.java:150)
        at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:77)
        at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:109)
        at com.yss.datamiddle.flinkYarnSubmiter.utils.JobGraphBuildUtil.buildJobGraph(JobGraphBuildUtil.java:75)
        at com.yss.datamiddle.flinkYarnSubmiter.executor.YarnJobClusterExecutor.submit(YarnJobClusterExecutor.java:73)
        at com.yss.datamiddle.flinkYarnSubmiter.launcher.LauncherMain.submitFlinkJob(LauncherMain.java:55)
        at com.yss.datamiddle.flinkYarnSubmiter.launcher.LauncherMain.main(LauncherMain.java:188)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:288)
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:198)
        at org.apache.flink.client.program.PackagedProgramUtils.getPipelineFromProgram(PackagedProgramUtils.java:150)
        at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:77)
        at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:109)
        at com.yss.datamiddle.flinkYarnSubmiter.utils.JobGraphBuildUtil.buildJobGraph(JobGraphBuildUtil.java:75)
        at com.yss.datamiddle.flinkYarnSubmiter.executor.YarnJobClusterExecutor.submit(YarnJobClusterExecutor.java:73)
        at com.yss.datamiddle.flinkYarnSubmiter.launcher.LauncherMain.submitFlinkJob(LauncherMain.java:55)
        at com.yss.datamiddle.flinkYarnSubmiter.launcher.LauncherMain.main(LauncherMain.java:188)
       ......
